# Generated by Django 3.2.15 on 2022-09-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='content',
            new_name='description',
        ),
    ]
